### ISSUE TITLE
example html file?

### ISSUE THREAD

**Issue by thesleort** [Kalyzee/gst-webkit#1]
First off, I must say it is a very nice plugin and looks very promising. I've been looking for something like this for a while. 

1. Is it required to run a webserver? 
2. Is there an example overlay html file to display? I have tried getting 
```
gst-launch-1.0 videotestsrc ! video/x-raw, format=RGBA, width=1280, height=720 ! mixer.sink_0   webkitsrc  url="localhost:1337" ! video/x-raw, format=RGBA, width=1280, height=720 ! alpha method=green ! mixer.sink_1   videomixer name=mixer sink_0::zorder=0 sink_1::zorder=1 !  videoconvert ! autovideosink sync=FALSE
```
 to work from the documentation. I am running a sailsjs server to test it. However, I am not able to see anything but the `videotestsrc` in the playback window. I am not sure if it is my html file or what I am doing wrong to display the html in the stream. I recon that this is on TODO, so I am not sure what to expect from it.

I have also tried running 
```
gst-launch-1.0 webkitsrc url=http://localhost:1337 ! video/x-raw, format=RGBA, framerate=25/1, width=1280, height=720 ! videoconvert ! xvimagesink sync=FALSE
```
This is displaying a black window. 

Am I doing something wrong or is it not fully developed yet?

**Comment by thesleort** [comment]
Okay I've added file load support (only very basic for development purposes atm.). However, it still doesn't show any html overlay.
https://github.com/thesleort/gst-webkit

**Comment by thesleort** [comment]
Nevermind. I fixed both issues in my fork

**Comment by michael-riha** [comment]
@thesleort I have the same Issue as I am running it in docker, I have troubles to debug.

Can you describe how you fixed this black screen? 

I also tried your fork but I have STATE Issue when encoding it to a file. 🤔

**Comment by thesleort** [comment]
I can't really remember what actually fixed it, however, webkit2gtk has one requirement for local files, which is, that it will only load files in the current directory you are in or any sub directories. This means, that you have to run `gst-launch-1.0` in the same directory or a parent directory to where your local file is located.
